
import SideBar from "@/components/Admin/Sidebar/SideBar";
import type { Metadata } from "next";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex mt-20">
        <div className="sidebar w-[20%]">
            <SideBar/>
        </div>
        <div className="mt-20 w-[76%] ">
        {children}
        </div>
    </div>     
       
     
     
  );
}
