import ButtonSection from "@/components/Dashboard/ButtonSection";
import SideBar from "@/components/Dashboard/SideBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mt-20 ">
      <div className="w-full min-h-[300px] flex justify-center place-items-center bg-gray-200">
        <h1 className="text-4xl">My Account</h1>
      </div>
      <ButtonSection/>
      <div className="mt-4 flex w-full container mx-auto md:flex-row flex-col gap-5">
     
            <SideBar/>
        
        <div className="flex-grow">{children}</div>
      </div>
    </div>
  );
}
